version: 2.1

orbs:
  cypress: cypress-io/cypress@3

executors:
  custom-node-executor:
    docker:
      - image: cypress/base:18.18.0

jobs:
  cypress-tests:
    executor: custom-node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build project
          command: npm run build
      - run:
          name: Start production server
          command: |
            npm run start &
            npx wait-on http://localhost:3000
      - run:
          name: Run Cypress Tests
          command: npx cypress run --browser chrome

workflows:
  build-and-test:
    jobs:
      - cypress-tests
